# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute the app, save build artifacts, and more:
# # https://docs.microsoft.com/azure/devops/pipelines/ecosystems/xcode

trigger:
- master

pool:
  vmImage: 'macOS-10.14'

variables:
  scheme: 'iOSHelloWorld'
  sdk: 'iphoneos'
  configuration: 'Debug'

steps:
- task: Xcode@5
  inputs:
    actions: 'clean build'
    sdk: '$(sdk)'
    scheme: '$(scheme)'
    configuration: '$(configuration)'
    xcodeVersion: 'default' # Options: default, 10, 9, 8, specifyPath
    exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
    packageApp: true
    signingOption: auto
    signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
    provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'
    exportMethod: development
    exportTeamId: 295V93MN3X
    teamId: 295V93MN3X
