# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute the app, save build artifacts, and more:
# # https://docs.microsoft.com/azure/devops/pipelines/ecosystems/xcode

trigger:
- master

pool:
  vmImage: 'macOS-10.14'

variables:
  scheme: 'iOSHelloWorld'
  sdk: 'iphoneos'
  configuration: 'Release'

steps:
- task: Xcode@5
  inputs:
    actions: 'clean build'
    sdk: '$(sdk)'
    scheme: '$(scheme)'
    configuration: '$(configuration)'
    xcodeVersion: 'default' # Options: default, 10, 9, 8, specifyPath
    exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
    packageApp: true
    teamId: 3B4S23SFDK

- task: ArchiveFiles@2
  displayName: 'Package .xcarchive into a zip file'
  inputs:
    rootFolderOrFile: '$(agent.buildDirectory)/output/$(sdk)/$(configuration-staging)'
    archiveType: 'zip'
    archiveFile: '$(build.artifactStagingDirectory)/iOSHelloWorld-$(Build.BuildId).zip'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)/iOSHelloWorld-$(Build.BuildId).zip'
    artifactName: 'iOSHelloWorld-$(Build.BuildId).zip'
    artifactType: 'container'
